# Exported from Render on 2025-12-25T13:49:47Z
version: "1"
services:
- type: web
  name: discord-stayonline
  runtime: docker
  repo: https://github.com/pyyupsk/discord-stayonline
  plan: free
  envVars:
  - key: DATABASE_URL
    sync: false
  - key: PORT
    sync: false
  - key: API_KEY
    sync: false
  - key: DISCORD_TOKEN
    sync: false
  region: singapore
  healthCheckPath: /health
  dockerContext: .
  dockerfilePath: ./Dockerfile
  autoDeployTrigger: commit
  buildFilter:
    paths:
    - cmd/**
    - internal/**
    - web/**
    - go.mod
    - go.sum
    - Dockerfile
    - Makefile
    ignoredPaths:
    - "**/*_test.go"
